- .golangci.yml
- go.mod
- go.sum
- internal/provider/upgrade.go
- tests/decentralized_test.go
- tests/install_qrcode_test.go
- tests/tests_suite_test.go
- tests/upgrade_k8s_test.go
- tests/upgrade_latest_k8s_test.go
switches to peg to align with kairos and tries to fix tests #19
> :robot: Use peg for machine testing library

- Earthfile
This workarounds #27 until we have selinux support https://github.com/kairos-io/kairos/issues/114
> :bug: Skip selinux install

- Earthfile
Signed-off-by: Ettore Di Giacinto <mudler@users.noreply.github.com>
> :arrow_up: Bump osbuilder image

- .github/workflows/image.yaml
- internal/provider/assets/cloudconfig.go
- internal/provider/vpn.go
- tests/assets/kubernetes_logs.sh
- tests/assets/single.yaml
- tests/decentralized_test.go
- tests/tests_suite_test.go
- tests/upgrade_k8s_test.go
- tests/upgrade_latest_k8s_test.go
Fixes https://github.com/kairos-io/kairos/issues/374
> :seedling: Generically configure dns with full-p2p enabled

- .github/bump_k3s_versions.sh
- .github/workflows/bump_core.yml
- .github/workflows/bump_k3s.yml
- .github/workflows/bump_repos.yml
Also, use signoff
Signed-off-by: mudler <mudler@c3os.io>
> :robot: Fix versions bump to be uniques

- README.md
> Fix link to image support matrix in the docs.

- internal/cli/start.go
Fix https://github.com/kairos-io/kairos/issues/509.
> Fix broken documentation about pairing

- internal/cli/register.go
This is a possible fix for https://github.com/kairos-io/kairos/issues/568.
> Check that QR file paths are readable and are not directories

- Earthfile
- internal/cli/register.go
- internal/cli/rotate.go
- internal/cli/start.go
- internal/provider/p2p.go
- internal/role/common.go
- internal/role/p2p/master.go
Partial fix for https://github.com/kairos-io/kairos/issues/643
> :seedling: add version information directly from git

- Earthfile
Signed-off-by: mudler <mudler@c3os.io>
> :penguin: Add nohang

- .github/workflows/image.yaml
- .github/workflows/release-arm.yaml
- .github/workflows/release.yaml
after bumping to v2:
https://blog.sigstore.dev/cosign-2-0-released/
> :robot: Fix cosign signing

- .github/workflows/image-arm.yaml
- .github/workflows/image.yaml
- .github/workflows/release-arm.yaml
- .github/workflows/release.yaml
Part of https://github.com/kairos-io/kairos/issues/1005
> Fix cosign errors with image digest

- .github/workflows/image-arm.yaml
- .github/workflows/image.yaml
like we do in the `image.yaml` pipeline too
Fixes: https://github.com/kairos-io/kairos/issues/1005 (hopefully)
> Use `latest` when building from `main`

- .github/workflows/release-arm.yaml
relates to kairos-io/kairos#770
> :robot: Push arm images to different repo

- Earthfile
relates to https://github.com/kairos-io/kairos/issues/1435
> :bug: Use lvm by default on rpi

- earthly.sh
- renovate.json
No need to wait on build for this one
> Add renovate config for earthfile and script

- go.mod
- go.sum
- internal/provider/p2p.go
Its only used in a function that is never called, so it doesnt make sense to keep 1 deps just for that.
> :arrow_up: Drop yip direct dep

- Earthfile
Fixes the current issue on main
> :bug: Set iso name for netboot

- releases.json
> :bug: Add rockylinux to standard releases

- internal/role/p2p/master.go
related to: https://github.com/kairos-io/kairos/issues/1797
> fix: better error messages

- internal/services/edgevpn.go
Fixes https://github.com/kairos-io/kairos/issues/2789
> Pass flags to edgevpn, not supervise_daemon

- internal/provider/bootstrap.go
And read args from both k3s or k0s
> Run bootstrap if k0s config is present

- go.mod
- go.sum
Reverts kairos-io/provider-kairos#818
> Revert "fix(deps): update module github.com/urfave/cli/v2 to v3"

- internal/provider/bootstrap.go
- internal/provider/config/config.go
- internal/role/p2p/k0s.go
- internal/role/p2p/k3s.go
- internal/role/p2p/k3s_test.go
- internal/role/p2p/k8s.go
- internal/role/p2p/k8s_test.go
- internal/role/p2p/kubevip.go
- internal/role/p2p/master.go
- internal/role/p2p/worker.go
- internal/role/schedule.go
This fixes the issue when user specifically set k8s to be disabled
fixes https://github.com/kairos-io/kairos/issues/3561
> Let the user disable k8s
