go.mod, go.sum, internal/provider/upgrade.go, tests/provider_upgrade_test.go
Part of the fix for: https://github.com/kairos-io/kairos/issues/249
We also need to select the last item instead of the first here:  https://github.com/kairos-io/kairos/blob/c141ea17923888c1b484fdbec09925c8b2febb26/internal/agent/upgrade.go#L54 
and optionally show a prompt to the user to confirm the version before doing the ugprade (unless some cli flag is passed to confirm automatically)
@mudler maybe we should exclude "rc" versions and such (everything non-stable)?
=> :bug: choose latest version on upgrade

internal/provider/upgrade.go, tests/provider_upgrade_test.go
because all our versions are considered pre-releases in standard semantic versioning. E.g.
v1.0.0-k3sv1.23.9-k3s1
this also has a "pre-release" part (everything after the `-`).
=> Remove the "stable" filtering in available_release response

Earthfile
SELinux has its own story: https://github.com/kairos-io/kairos/issues/114. We temporary disable it here, as there is no support at OS level currently.
Fixes: https://github.com/kairos-io/kairos/issues/376
See also pipeline failures at: https://github.com/kairos-io/provider-kairos/actions/runs/3665967843
Signed-off-by: mudler <mudler@c3os.io>
=> :bug: Skip SELINUX warnings in fedora builds

internal/provider/bootstrap.go
p2p block is optional, thus we might panic otherwise here
Signed-off-by: Ettore Di Giacinto <mudler@users.noreply.github.com>
=> :bug: Fixup detection if block is missing

go.mod, go.sum, internal/cli/bridge.go, internal/cli/start.go
With the upgrade of the cli pkg, making flags required is very simple, it just needs an attribute `required: true`
Fixes https://github.com/kairos-io/kairos/issues/375
:warning: breaking UX change
> In v2 flags must come before args. This is more POSIX-compliant. You may need to update scripts, user documentation, etc.
This means that 
```
provier-kairos command ARG FLAG
```
is no longer valid, but I still think the change is worth it because like the documentation says, the CLI will be more POSIX-compliant
=> Upgrade urfave/cli and make register's config flag required

.github/workflows/release_bin.yaml
- upgrade go version to 1.18 to fix https://github.com/kairos-io/kairos/issues/589
- add a mechanism to test gorelease by prefixing your branch with `test-goreleaser/`
=> Test goreleaser/upgrade to go1.18

Earthfile, internal/provider/upgrade.go, tests/provider_upgrade_test.go
and fix renamed Earthly ARG
Fixes https://github.com/kairos-io/kairos/issues/598
Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>
=> Exclude `.img` images from upgrades

.github/workflows/image-arm.yaml, .github/workflows/image.yaml, Earthfile
Based on the new tumbleweed flavor for kairos
Blocked until https://github.com/kairos-io/kairos/pull/710 gets in and pushes the new flavor
Signed-off-by: Itxaka <itxaka@spectrocloud.com>
=> :warning: Add tumbleweed flavor

.github/bump_k3s_versions.sh, releases-arm.json, releases.json
I forgot this script so on 1.5.0 nothing opensuse related was build and published due to the name change
Signed-off-by: Itxaka <itxaka@spectrocloud.com>
=> Adds newer flavors to the bump_k3s_versions script

.github/workflows/image.yaml, Earthfile
We didn't called `apt-get update` before installing nohang, so it wasn't found in the repo. I've also added the `debian` flavor to the build job of the CI so we can spot those issues before.
Fixes: https://github.com/kairos-io/kairos/issues/970
=> :bug: Remove debian specific block

Earthfile
We can't use VERSION, as we have a bigger matrix consisting of k3s versions too. that lead to each job to replace the sbom of another one:
```
Run softprops/action-gh-release@v1
⬆️ Uploading kairos-alpine-opensuse-leap-v2.0.0-rc3-k3sv1.21.14+k3s1-initrd...
⬆️ Uploading kairos-alpine-opensuse-leap-v2.0.0-rc3-k3sv1.21.14+k3s1-ipxe-usb.img.ipxe...
⬆️ Uploading kairos-alpine-opensuse-leap-v2.0.0-rc3-k3sv1.21.14+k3s1-ipxe.iso.ipxe...
⬆️ Uploading kairos-alpine-opensuse-leap-v2.0.0-rc3-k3sv1.21.14+k3s1-kernel...
⬆️ Uploading kairos-alpine-opensuse-leap-v2.0.0-rc3-k3sv1.21.14+k3s1.ipxe...
⬆️ Uploading kairos-alpine-opensuse-leap-v2.0.0-rc3-k3sv1.21.14+k3s1.iso...
⬆️ Uploading kairos-alpine-opensuse-leap-v2.0.0-rc3-k3sv1.21.14+k3s1.iso.sha256...
⬆️ Uploading …
```
=> :robot: Version SBOM after TAG

.github/workflows/release_bin.yaml, .goreleaser.yaml, Earthfile
Pass the version to goreleaser, so the artifact that can be dowloaded includes it
relates to kairos-io/kairos#1249
=> :robot: Add version to goreleaser

.github/workflows/image-arm.yaml, .github/workflows/release-arm.yaml, Earthfile
Builds and releases oci artifacts and ISOs for release pipelines.
Also reworks a bit the master pipeline for arm generic to push to the master tag instead of latest.
Also generates sboms as part of both pipelines
=> :robot: Release arm64 generic artifacts

releases-arm.json
I missed the fact that the releases were a different source than the build
Relates to kairos-io/kairos#1439
=> :penguin: Add ubuntu versions to the arm releases matrix

Earthfile
A bunch has happened between 0.6.7 and 0.7.4, we probably want the latest since it brings the lvm support and other things
=> Bump osbuilder version

Earthfile
golang official image no longer has the upx binary available. If we want to keep on the latests we should not fix the image to bullseye and keep on the current and future version tag for golang.
This patch drops upx and just uses the golang image for golang deps.
Fixes https://github.com/kairos-io/kairos/issues/1521
=> Drop upx compression

.github/bump_k3s_versions.sh
Currently we are building for anything higher than k8s 1.20 which is not maintainable with our flavor matrix.
This patch fixes the script to only output the upstream supported versions (latest + 2) and also adds some output to the building process to be able to see what is doing
=> :art: Rework supported k3s versions

Earthfile
so that provider images don't show "core" as variant
Fixes: https://github.com/kairos-io/kairos/issues/1536
=> Pass VARIANT to OSRELEASE target

.goreleaser.yaml
because somehow the end up as `.` in the final artifact in Github releases (probably because [Github converts spaces to dots](https://github.com/cli/cli/issues/7024#issue-1592370641)).
Fixes https://github.com/kairos-io/kairos/issues/1520
=> Don't add spaces to artifact names

.goreleaser.yaml, Earthfile, README.md, cli/kairosctl/main.go, go.mod, internal/cli/config_test.go, internal/cli/recovery_darwin.go, internal/cli/rotate.go, internal/cli/start.go, internal/provider/bootstrap.go, internal/provider/bootstrap_test.go, internal/provider/challenge.go, internal/provider/challenge_test.go, internal/provider/p2p.go, internal/role/auto.go, internal/role/p2p/common.go, internal/role/p2p/kubevip.go, internal/role/p2p/master.go, internal/role/p2p/worker.go, internal/role/schedule.go, main.go, tests/e2e/ha_test.go, tests/e2e/proxmox.go
The path in `go.mod` should be ended in `/v2` suffix, as per [go.mod module version numbers](https://go.dev/doc/modules/version-numbers).
=> fix: bump go.mod path to v2

.github/workflows/image.yaml
We now have some flavors upstream under kairos which only provide framework images, so we cant build those as part of the normal workflow.
This basically copies the fix from Dimitris in the kairos repo to skip the frameworkonly flavors
Should fix the current CI issue
=> :robot: Build only non framework flavors

.github/workflows/image-arm.yaml, .github/workflows/lint.yml, .github/workflows/test.yml
Otherwise we just queue 30 jobs for each if we merge in succession.
=> :robot: Add concurrency to all jobs

internal/cli/start.go
so that we can call it to verify we built a fips version by greping for "boringcrypto" in the output.
Part of: https://github.com/kairos-io/kairos/issues/1609
Will be used here: https://github.com/kairos-io/packages/pull/334
=> Add golang information to the --version output 

Earthfile
Pass flavor to `OSRELEASE` to not use default one defined at https://github.com/kairos-io/kairos/blob/master/Earthfile#L4.
Issue : https://github.com/kairos-io/kairos/issues/1607
=> Fix flavor is not the core one for the provider images

Earthfile
relates to kairos-io/kairos#1109
`earthly +all`
```
kairos-standard-opensuse-leap-amd64-generic-v2.3.1-dirty-k3s-initrd
kairos-standard-opensuse-leap-amd64-generic-v2.3.1-dirty-k3s.ipxe
kairos-standard-opensuse-leap-amd64-generic-v2.3.1-dirty-k3s-ipxe.iso
kairos-standard-opensuse-leap-amd64-generic-v2.3.1-dirty-k3s-ipxe-usb.img
kairos-standard-opensuse-leap-amd64-generic-v2.3.1-dirty-k3s.iso
kairos-standard-opensuse-leap-amd64-generic-v2.3.1-dirty-k3s.iso.sha256
kairos-standard-opensuse-leap-amd64-generic-v2.3.1-dirty-k3s-kernel
kairos-standard-opensuse-leap-amd64-generic-v2.3.1-dirty-k3s-sbom.spdx.json
kairos-standard-opensuse-leap-amd64-generic-v2.3.1-dirty-k3s-sbom.syft.json
kairos-standard-opensuse-leap-amd64-generic-v2.3.1-dirty-k3s.squashfs
```
`earthly +all-arm-generic …
=> :sparkles: Introduce new artifact naming convention

Earthfile, internal/provider/bootstrap.go, internal/role/p2p/master.go, internal/role/p2p/worker.go
No longer used, move to kairos-agent
Also drop sha iso calculation as its done by the iso builder automatically
Fixes https://github.com/kairos-io/kairos/issues/1798
=> Drop elemental calls

internal/provider/interactive-install.go
It was being set to kairos key but the proper key is p2p
Fixes: https://github.com/kairos-io/kairos/issues/1922
=> Set the proper yaml section for p2p

.github/workflows/release_bin.yaml, .goreleaser.yaml, go.mod
* drop rlcp: true -> https://goreleaser.com/deprecations#sourcerlcp
* switch to --clean arg -> https://goreleaser.com/deprecations#-rm-dist
* pin golang version -> https://github.com/kairos-io/provider-kairos/actions/runs/6123251646/job/16620757329#step:7:224
=> :bug: Fix kairosctl goreleaser build

internal/provider/bootstrap.go
Somehow on systemd 245 (245.4-4ubuntu3.22) becuase the k3s file was created with no content, it marked it as a masked service and nothing would work as expected.
Creating the file with empty service and execstart makes the service not appear as masked and allows the override to work as expected
This patch also adds more logging to the log file, and writing the service file before starting it.
```
root@qcs6490-odk:~# systemctl status k3s
Warning: The unit file, source configuration file or drop-ins of k3s.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● k3s.service
Loaded: masked (Reason: Unit k3s.service is masked.)
Drop-In: /etc/systemd/system/k3s.service.d
└─override.conf
Active: inactive (dead)
```
=> Create empty k3s service file

internal/provider/config/config.go, internal/role/p2p/kubevip.go
Closes https://github.com/kairos-io/kairos/issues/1993
To use:
```
kubevip:
static_pod: true
```
I'm still getting my build environment set up so unfortunately I can't test this functionality myself but the change should be straightforward. Please review with this in mind, I definitely could have missed something.
=> feat(kubevip): static pod support

go.mod
v2.6.5 uses 1.21 and didn't break on release
Just want to have another pair of 👀 in case there was something else related to this comment
=> Remove warning preventing to bump Go version

go.mod, go.sum, internal/cli/bridge.go, internal/cli/recovery.go
Just a cleanup left from last weeks work
=> :sparkles: Refactor edgevpn integration

internal/provider/config/config.go, internal/role/p2p/master.go
This is a simple way to enable Spegel with k3s by following https://docs.k3s.io/installation/registry-mirror?_highlight=spegel .
Part of https://github.com/kairos-io/kairos/issues/3100
=> feat(embedded registry): allow to enable embedded registry

internal/cli/role.go, internal/role/p2p/k0s.go, internal/role/p2p/master.go, internal/role/p2p/worker.go
It also extends the `role list` command to show the edgevpn ips of the nodes so it's easier to just jump to the clusterinit one and manage the cluster from there
=> Add p2p ha configuration for k0s

internal/role/p2p/k3s.go, internal/role/p2p/k3s_test.go, internal/role/p2p/suite_test.go
Part of: https://github.com/kairos-io/kairos/issues/3100
fixing the manual setup case.
A config similar to this should now work:
master:
```yaml
hostname: metal-{{ trunc 4 .MachineID }}
users:
- name: kairos # Change to your own user
passwd: kairos # Change to your own password
groups:
- admin # This user needs to be part of the admin group
k3s:
enabled: true
embedded_registry: true
stages:
boot:
- name: "Add registries configuration for k3s/spegel"
files:
- path: /etc/rancher/k3s/registries.yaml
content: |
mirrors:
"*":
```
worker:
```yaml
#cloud-config
hostname: metal-{{ trunc 4 .MachineID }}
users:
- name: kairos # Change to your own user
passwd: kairos # Change to your own password
groups:
- admin # This user needs to be part of the admin group
k3s-agent: # Warning: the key is …
```
=> 3100 fix embedded registry config
